### ISSUE TITLE
Trying to compile on Mac OS 10.12.6

### ISSUE THREAD

**Issue by fluxly** [possan/libpd-esp32#1]
Thanks for starting this project! I'm trying to get it working on my mac and was running into this missing path/include when compiling pure data:

/esp/project/components/libpd/libpd/pure-data/src/s_inter.c:20:22: fatal error: sys/mman.h: No such file or directory

I'm not entirely clear if I have the correct SDK (I'm using https://github.com/espressif/esp-idf), or if I'm missing something in the docker configuration. Any suggestions? And just saying "use Linux" is fine as well.

Thanks
